### ISSUE TITLE
[Feature Request] Option to operate the same as the N64 Console

### ISSUE THREAD

**Issue by jonaeru** [fgsfdsfgs/perfect_dark#161] opened 2023-09-09 03:38 UTC
I am familiar with the N64 controller and would like to perform the same operation if possible. I am connecting in DIrectInput format.
I tried playing with the "Use / Cancel" (B) and "Reload" (X) assigned to the B button and it reloads every time I open the door, which is troubling if I have the Mauler charge-up equipped.
How about preparing a special flag for N64 controllers?

EDIT: It would be nice to be able to place a cam spy with the A button.
The door opens by pressing the A button, so if I change the weapon in front of the door the door opens and I am in trouble.

| Action                       | Keyboard and mouse | Xbox pad | N64 pad    | N64 pad (Console) |
| -                            | -                  | -        | -          | -                 |
| Fire / Accept                | LMB/Space          | RT       | Z Trigger  | Z Trigger         |
| Aim mode                     | RMB/Z              | LT       | R Trigger  | R Trigger         |
| Use / Cancel                 | E                  | N/A      | B          | B                 |
| Use / Accept                 | N/A                | A        | A          | A **(No "Use")**  |
| Reload                       | R                  | X        | X `(0x40)` | **B**             |
| Previous weapon              | Mousewheel forward | B        | D-Left     | **A + Z**         |
| Next weapon                  | Mousewheel back    | Y        | Y `(0x80)` | **A**             |
| Radial menu                  | Q                  | LB       | D-Down     | **A Hold**        |
| Alt fire mode                | F                  | RB       | L Trigger  | **B Hold**        |
| Alt fire mode (Temporarilly) | F + LMB            | RB + RT  | L + Z      | **B + Z**         |
| Quick-detonate               | E + Q              | A + B    | A + D-Left | **A + B**         |

**Comment by Atari-Dude** [comment] 2023-09-09 07:11
I agree and I hope it's possible to bring the "press and hold" functionality to keyboard as well. With my current keyboard mappings, reloading with [C] automatically switches weapon functions as well because I've mapped them to the same key as that's my muscle memory from playing PD64 on original hardware for so long. But because there's no option to re-enable "press and hold", you get stuff like this lol

https://github.com/fgsfdsfgs/perfect_dark/assets/66316465/5c9ebe2b-2626-42d4-8fdf-7b2c8a416769

**Comment by Graslu** [comment] 2023-09-16 01:24
Yes it'd be appreciated if we could have proper N64 controller support. Raphnet Adapter support would be ideal since it's 1:1 to real N64 hardware.

**Comment by LanHikariDS** [comment] 2023-09-19 04:52
Best overall solution I think would be having a toggle in the .ini for Xbox (current default) or N64 controller type for each player, since there are dozens of different N64 adapters, not to mention the Switch N64 controller, and likely N64-styled USB controllers as well.

**Comment by fgsfdsfgs** [comment] 2023-09-20 07:59
So what features from the N64 control scheme would you need? The press-and-hold reload, what else? Need an exact list of what to enable/disable when the "N64 control mode" is on.

**Comment by Graslu** [comment] 2023-09-20 09:03
B hold for mode swap, A hold for radial menu, B for reload and use, if crouching is added to an independent key then allow crouching by aiming + pressing back on movement.

>since there are dozens of different N64 adapters

Yes but most if not all of those will be recognized as controllers right away and allow for remapping, while also wrongly detecting C-Buttons as a second stick. I believe Raphnet doesn't get detected automatically unless supported, but I'll have to test this.

**Comment by jonaeru** [comment] 2023-09-20 11:05
The following operations are currently not possible, so it would be great to be able to set the following.

| Action                       | Keyboard and mouse | Xbox pad | N64 control mode  | Note                                  |
| -                            | -                  | -        | -                 | -                                     |
| Use / Accept                 | N/A                | A        | A                 | Disable "Use"                         |
| Reload                       | R                  | X        | B                 | "Use" is priority, otherwise "Reload" |
| Previous weapon              | Mousewheel forward | B        | A + Z             | -                                     |
| Radial menu                  | Q                  | LB       | A Hold            | Enable "Hold"                         |
| Alt fire mode                | F                  | RB       | B Hold            | Enable "Hold"                         |
| Alt fire mode (Temporarilly) | F + LMB            | RB + RT  | B + Z             | -                                     |
| Quick-detonate               | E + Q              | A + B    | A + B             | -                                     |

**Comment by Gorilli09** [comment] 2023-09-22 00:48
Off topic, but the Xbox controls needs to be based off of TimeSplitters and XBLA Perfect Dark.

**Comment by cylonicboom** [comment] 2023-11-02 03:14
> The following operations are currently not possible, so it would be great to be able to set the following.
> Action 	Keyboard and mouse 	Xbox pad 	N64 control mode 	Note
> Use / Accept 	N/A 	A 	A 	Disable "Use"
> Reload 	R 	X 	B 	"Use" is priority, otherwise "Reload"
> Previous weapon 	Mousewheel forward 	B 	A + Z 	-
> Radial menu 	Q 	LB 	A Hold 	Enable "Hold"
> Alt fire mode 	F 	RB 	B Hold 	Enable "Hold"
> Alt fire mode (Temporarilly) 	F + LMB 	RB + RT 	B + Z 	-
> Quick-detonate 	E + Q 	A + B 	A + B 	-

`B + Z` alt-fire oneshot should be working right now.

I added more buttons so I can move the "extra" buttons for 1964/xbox parity to those slots. Then the other things are straightforward to restore & run conditionally based on the expanded controller options settings.

**Comment by BiatuAutMiahn** [comment] 2023-11-02 04:25
When I use an Xbox controller for N64 emu I usually set these:
```
A = A
B = B
Z = RT, LT (Both Z)
L = LB
R = RB
```

**Comment by jonaeru** [comment] 2023-11-02 13:34
@NeonNyan
> B + Z alt-fire oneshot should be working right now.

Thank you, it worked, but "Next Weapon" and "Reload" also worked at the same time.

I made the following assignments.
Fire / Accept: Z
Use / Accept: A
Use / Cancel: B
Reload: B
Next weapon: A

Alt-fire oneshot
[Use / Accept] + [Fire / Accept]: A + Z (A: Next weapon also works)
[Use / Cancel] + [Fire / Accept]: B + Z (B: Reload also works, sometimes not work Alt-fire oneshot)
[Alt fire mode] + [Fire / Accept]; L + Z

Quick-detonate
[Use / Accept] + [Reload]: A+B (A: Next weapon also works)
[Use / Accept] + [Previous weapon]: A+D-Left

On another matter, `StickCButtons=0` in pd.ini is not working.

**Comment by fgsfdsfgs** [comment] 2023-11-02 13:53
What do you mean not working?
When it's set to `1`, left analog stick generates C button presses, resulting in "digital" movement.
When it's set to `0`, left analog stick acts as a real analog stick, resulting in analog movement.
I can definitely reproduce the correct behavior locally. Maybe you need to update your build? If you're building locally, try doing a `make -f Makefile.port clean` first.

**Comment by jonaeru** [comment] 2023-11-03 01:29
I used the artifact. https://github.com/fgsfdsfgs/perfect_dark/actions/runs/6726244516.

Sorry, this may be a slightly different case.
I am imagining the control style 1.2. 
Stick: Look
C button: Move

In previous builds, if `StickCButtons=0`, the stick was only for viewpoint movement. In the latest build, viewpoint movement and movement are combined.

**Comment by cylonicboom** [comment] 2023-11-03 03:59
Hi @jonaeru, I just tried the jpn build. It seems to be behaving correctly.

**Comment by cylonicboom** [comment] 2023-11-03 04:00
I can't reproduce the movement and aim movement being combined on one stick, either on ntsc-final or jpn-final.

**Comment by jonaeru** [comment] 2023-11-03 04:31
Thank you. I think I may have found the cause somewhat.
I have an N64 controller connected in DirectInput, with only one stick. the L stick and R stick seem to be working at the same time.

I solved the problem by setting L Stick Scale to 0!
![image](https://github.com/fgsfdsfgs/perfect_dark/assets/64701608/60a09ad4-53b7-49d8-b4f3-5877c1e0a29d)

**Comment by fgsfdsfgs** [comment] 2023-11-03 08:23
Seems that the one stick on the controller somehow maps to both left and right stick in SDL. That's quite weird and is probably a quirk of that particular controller or adapter. In this case yeah, just setting sensitivity for one of the sticks to 0 is the easiest solution.
As a side note, I should probably add support for loading SDL `gamecontrollerdb` files, then you could configure any exotic controller to your liking.

**Comment by jonaeru** [comment] 2023-11-04 07:11
I used 407d472 build.

### Assignment
- Fire / Accept: Z
- Use / Accept: A
- Use / Cancel: B
- Reload: B
- Previous weapon: D-Left
- Next weapon: A
- Alt fire mode: L

### Alt-fire oneshot
The following worked, but if I assign A to Next weapon and B to Reload, they may get in the way.
Remote Mines appear to behave strangely with "Unlimited Ammo, No Reloads".

[Use / Accept] + [Fire / Accept]: A + Z
[Use / Cancel] + [Fire / Accept]: B + Z
[Alt fire mode] + [Fire / Accept]; L + Z

### Quick-detonate
The following worked, but change "Unarmed" after detonation.
With the above assignment, just pressing the B button will detonate the bomb, but the B button will not open the door.
When Quick-detonate is performed while moving, the movement stops.

[Use / Cancel] + [Reload]: B + B (B + X)
[Use / Accept] + [Reload]: A + B (A + X)
[Use / Accept] + [Previous weapon]: A + D-Left


https://github.com/fgsfdsfgs/perfect_dark/assets/64701608/bbaffeed-adb3-4d04-80f2-14e549186946

**Comment by cylonicboom** [comment] 2023-11-07 06:17
I submitted a PR which will help with the remote mine selection issues: https://github.com/fgsfdsfgs/perfect_dark/pull/230

I'll take a look at the unlimited ammo + remote mine scenario.

Like @fgsfdsfgs said the N64ness should be restored per-item w/ a config entry (which makes sense now that we have extra buttons to accommodate and per-player configs.)

**Comment by fgsfdsfgs** [comment] 2023-11-26 17:17
I've added (partial?) support for the original control schemes. The "PC port" control scheme that the port had before is now a separate scheme called Ext and is the default. Note that if you change to an N64 scheme you'll have to rebind some buttons anyway, since there's only one set of bindings in the config and it's set to reasonable defaults for the PC scheme. I'll probably add another one for N64 schemes later.

**Comment by jonaeru** [comment] 2023-12-07 00:19
Build: https://github.com/fgsfdsfgs/perfect_dark/actions/runs/7117212181 (aeb6851)

I was able to operate the same as the N64 console. Thank you!

![image](https://github.com/fgsfdsfgs/perfect_dark/assets/64701608/737404ce-66e7-4723-9f5b-fe45b4335f72)
![image](https://github.com/fgsfdsfgs/perfect_dark/assets/64701608/d24d1d06-8ef7-4c4c-8d09-c200923381a1)
![image](https://github.com/fgsfdsfgs/perfect_dark/assets/64701608/ac1aca69-3933-49f5-8785-1e4e0ab1edf6)

**Comment by fgsfdsfgs** [comment] 2023-12-07 15:49
Thanks for testing. I'll close this then. Feel free to bump this issue if there are any problems.

**Closed as completed by fgsfdsfgs** 2023-12-07 15:49 UTC

**Comment by FrostKnight** [comment] 2024-06-09 01:54
Is raphnet N64 V3 supported? I would love to be able to use it on my computer for this.

**Comment by fgsfdsfgs** [comment] 2024-06-09 10:46
Yes. If you don't have the Rumble Pak inserted set the vibration strength to 0 in the extended options, otherwise it will lag every time it attempts to vibrate due to a quirk in how the Raphnet adapter works.
