### ISSUE TITLE
[Feature Request] Fix double-reload bug

### ISSUE THREAD

**Issue by Graslu** [fgsfdsfgs/perfect_dark#109] opened 2023-08-28 17:15 UTC
The original Perfect Dark, including the XBLA remaster has a bug where sometimes the gun will automatically reload after you manually do it. This is extremely annoying and happens seemingly at random so it's hard to recreate, but if you've played a lot you know what I'm referring to.

This is specially noticeable with the Crossbow and Shotgun for some reason but it happens with all weapons. Here's a short example where I reloaded manually after depleting the magazine and then after shooting twice it auto-reloaded once again.

https://github.com/fgsfdsfgs/perfect_dark/assets/34986384/c2798f8d-970c-4eb9-9505-68cfce4894ab

**Comment by cylonicboom** [comment] 2023-08-29 14:44
Have you been able to reproduce this with the PC port?

**Comment by Graslu** [comment] 2023-08-29 14:47
Yes, that clip above is from the port.

**Comment by rafccq** [comment] 2023-08-29 15:32
I manage to reproduce it in the port. It's a little tricky to reproduce consistently, because you need a very strict timing in the reload.
Just a few frames after you shoot the last bullet/bow in the clip, press reload.

**Comment by cylonicboom** [comment] 2023-08-31 02:11
I just reproduced it. I ran into a similar issue with earlier builds of my mouse injector decomp reload patch, but that was a regression where it happened even when you explicitly reloaded (rather than draining it like @Graslu  did.)

**Comment by rafccq** [comment] 2023-09-03 16:41
@Graslu whenever you can please help check if this one fixes it: #121 
I can confirm it fixes it for shotguns and crossbow. For other weapons I can't reproduce either but can't be sure since its kinda hard to reproduce.

**Comment by Graslu** [comment] 2023-09-03 19:17
I tested #121, I can still reproduce it fairly consistently. Basically once the counter reaches 0, I spam R a few times and then quickly switch to shooting when the counter is going up. After a shot or two it'll automatically reload. Edit: I cut the video a bit too early, it occurs twice here but later I got it to happen more consistently.


https://github.com/fgsfdsfgs/perfect_dark/assets/34986384/44d31ccc-a383-454b-9c7c-59bfb7ad89ea

**Comment by Graslu** [comment] 2023-09-03 19:23
Also still able to reproduce it with #128.

https://github.com/fgsfdsfgs/perfect_dark/assets/34986384/94c0730c-77bb-4655-8328-1a428e85f407

**Comment by rafccq** [comment] 2023-09-03 19:27
Thanks, I'll look into it. Just checking: you tested using the correct build from the Actions tab right?

**Comment by cylonicboom** [comment] 2023-09-03 19:38
I just went and unlocked Unlimited Ammo and reproduced it in #128

**Comment by Graslu** [comment] 2023-09-03 21:53
> Thanks, I'll look into it. Just checking: you tested using the correct build from the Actions tab right?

Yeah, got both from there.

**Comment by cylonicboom** [comment] 2023-09-03 21:57
I just tried to repro this with gdb, which I couldn't but I get the idea to start blocking if the clip was full. I was still able to reproduce (without gdb)

Finally I merged @rafccq  and I's branch and I can still get it to repro sometimes.

**Comment by rafccq** [comment] 2023-09-05 14:49
New fix here, one line solved it apparently: #121
So, after getting tired of trying to reproduce this consistently, I wrote a script to send inputs to the game. I found that the problem happens when interspersing fire and reload inputs. The script can reproduce it consistently. So here's a video of running the script before the newest fix:

https://github.com/fgsfdsfgs/perfect_dark/assets/1994385/9743ef45-a3ea-4f39-aeb0-4ab9a2f2b2e8

And here running the same script after the fix: doesn't happen anymore:

https://github.com/fgsfdsfgs/perfect_dark/assets/1994385/22da25f8-d16a-464a-a6d3-5c2763af2849

**Comment by rafccq** [comment] 2023-09-05 14:55
[PD_ReloadTest.txt](https://github.com/fgsfdsfgs/perfect_dark/files/12524981/PD_ReloadTest.txt)
Here's the script in case anyone wants it (windows only, sorry), its an AutoIt V3 script.
@Graslu pls help test again with your superpowers, thanks! You can grab the build [here](https://github.com/fgsfdsfgs/perfect_dark/actions/runs/6085990272)

**Comment by Graslu** [comment] 2023-09-05 15:53
Seems like that fixes it! Haven't tried the script but my superpowers cannot recreate it any more even after absolutely spamming R until the last moment before shooting.

**Comment by rafccq** [comment] 2023-09-05 16:43
Ok nice! 
@fgsfdsfgs looks like this one is good to go.

**Closed as completed** 2023-09-08 10:59 UTC
Labels: n64 bug
