### ISSUE TITLE
Models "squish" on some spots

### ISSUE THREAD

**Issue by Graslu** [fgsfdsfgs/perfect_dark#19] opened 2023-08-16 11:11 UTC
Specially noticeable with mines, but also just had a guard do it in real time. Not sure what triggers it, seems to be dependant on the map geometry.

https://github.com/fgsfdsfgs/perfect_dark/assets/34986384/28b683d2-19d9-4a18-ba0f-30dc1c7bbb9f

![Base Profile Screenshot 2023 08 16 - 13 06 04 99](https://github.com/fgsfdsfgs/perfect_dark/assets/34986384/9c87e34a-e149-46ca-8d13-e29798f04e8e)

**Comment by ghost** [comment] 2023-08-19 14:37
The mine scaling issue seems to be consistent with whatever polygon of geometry it lands on. This varies within it's angle too (In the second example with the doors, the mine will be squished on one side, but fine on the other).

The guard issue I've not been able to reliably reproduce. It has happened to me once when changing the window aspect, but that seems like it's unrelated.

**Comment by fgsfdsfgs** [comment] 2023-08-20 14:30
This should be fixed now.

**Comment by ghost** [comment] 2023-08-20 15:13
Can confirm the issue with mines is fixed. Can't reproduce the guard squishing consistently so I can't confirm that, but it should be fixed if both stem from the same issue.

**Closed as completed** 2023-08-20 15:31 UTC
