### ISSUE TITLE
MacOS build issues

### ISSUE THREAD

**Issue by AJ292** [fgsfdsfgs/perfect_dark#537] opened 2024-11-19 23:20 UTC
Just tried to have a look at the automatic MacOS build and I'm wondering if there's additional steps or instructions needed specifically for it? For a start, the size is significantly smaller than the builds for Windows and Linux. Secondly, there doesn't seem to be a compiled app package for the various versions of the game - MacOS flags them as documents, not applications. MacOS apps technically have a .app file extension (it's not ever shown in the OS itself) - adding .app to the files then leads to a generic "could not open application" error.

I don't think the MacOS builds have been done correctly. I'm using the x86 version, but I assume that it's the same for the ARM version as well.

**Comment by fgsfdsfgs** [comment] 2024-11-20 01:01
There isn't a compiled package because:
1. I have no clue how to do that since I don't have any OSX devices and don't develop anything for OSX.
2. I'm pretty sure those have to be signed, and I have no way of doing that.

You can run the binary from the terminal, for example:
```
cd wherever/you/unpacked/the/build
chmod +x pd.x86_64
./pd.x86_64
```
The `chmod` part needs to only be done once. Replace `x86_64` with `arm64` for ARM Macs. Pretty sure after you do the `chmod` you'll be able to run it from Finder as well.

The reason it is smaller is because OSX uses a different executable format and apparently they're symbol stripped by default or compressed or something.

**Comment by AJ292** [comment] 2024-11-20 01:12
Gotcha. 

MacOS apps technically don't have to be signed, but it's more of a hassle for the end user (particularly on a more locked down system) as Gatekeeper will prevent it from loading - this is particularly eggregious on MacOS Sequioa. Regardless, totally understand the reasoning.

I'm currently working through getting SDL2 going on my system - will report back on your Terminal instructions when it's all done.

**Comment by fgsfdsfgs** [comment] 2024-11-20 01:14
`SDL2.framework` is bundled with the builds, though I'm not sure if it will get automatically loaded even if you don't copy it to `/Library/Frameworks/`. Have seen some other projects do this, so I hoped it'd work.

**Comment by AJ292** [comment] 2024-11-20 01:17
Unfortunately, it doesn't seem to:

```
dyld[22556]: Library not loaded: @rpath/SDL2.framework/Versions/A/SDL2
  Referenced from: <8424FA3C-9AEE-39C2-9009-B7F69941BD95> /Users/aj/Downloads/pd-x86_64-osx/pd.x86_64
  Reason: tried: '/Library/Frameworks/SDL2.framework/Versions/A/SDL2' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Library/Frameworks/SDL2.framework/Versions/A/SDL2' (no such file), '/Library/Frameworks/SDL2.framework/Versions/A/SDL2' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Library/Frameworks/SDL2.framework/Versions/A/SDL2' (no such file)
zsh: abort      ./pd.x86_64
```

**Comment by fgsfdsfgs** [comment] 2024-11-20 01:22
You might or might not be able to install it the same way the CI script does for now:
```
          wget http://libsdl.org/release/SDL2-2.30.9.dmg -O SDL2.dmg
          hdiutil mount SDL2.dmg
          sudo cp -vr /Volumes/SDL2/SDL2.framework /Library/Frameworks
```

I'll look into a more proper way of distributing it.

**Comment by fgsfdsfgs** [comment] 2024-11-20 01:27
Alternatively, try something like
```DYLD_LIBRARY_PATH=.:$DYLD_LIBRARY_PATH ./pd.x86_64```

It's likely that I need to build it with `-DCMAKE_MACOSX_RPATH=ON` or something similar for it to be able to load frameworks from the working directory. I'd need to test that.

**Comment by AJ292** [comment] 2024-11-20 01:39
I ended up manually installing the framework (wget doesn't work) which is a simple enough case of copying it into Library/Frameworks. Couple of minor things in Terminal after launch:

```
WARNING: GL: could not create GL3.0 context: Failed creating OpenGL context at version requested
GL: created GL3.2core context
WARNING: GL: using core profile, watch out for errors
```

In terms of bugs, I'm doing a quick run through now. The pause screen background just shows solid black instead of blurring the game, and going to Options > Extended > Controller > Player 1 causes an immediate crash (didn't seem to happen on any of the other players). I have a PS4 wireless dongle plugged in, which does seem to be recognised by the game according to the Terminal output so I'll try it again without that to see if it makes a difference. 

Also, the chmod command did not allow the app to be run from Finder either - it's still shown as a Document file type.

I'm more than happy to test things for you as well, but I'm very much an amateur - think surface level knowledge of Terminal and the backend of MacOS. If that's at all useful, then I'm on board. :)

**Comment by fgsfdsfgs** [comment] 2024-11-20 01:43
Might be a good idea to try running the game like so, unless your system is old enough to not support GL4.1:
```./pd,x86_64 --gl-version 4.1core```

Does it say anything in the terminal when it crashes with the controller?

**Comment by AJ292** [comment] 2024-11-20 01:48
Unfortunately, no. I'll try and get a detailed Console output for the crash.

Annoyingly, the game isn't even launching at all now, but let me do some things on my end first before I sound the alarm.

**Comment by AJ292** [comment] 2024-11-20 02:03
Ok, a couple of updates. Using GL 4.1 works fine (though it does warn about using the core profile for some reason). The black background instead of the blurred game is still present. Unplugging the PS4 dongle before launching the game and jumping into Player 1's extended controller options does not cause a crash so it certainly seems connected to the dongle.

I get this in Terminal, which I presume is not particularly helpful:

`zsh: segmentation fault  ./pd.x86_64 --gl-version 4.1core`

And Console shows this:

```
Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Codes:       0x0000000000000001, 0x0000000000000000

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [1142]

VM Region Info: 0 is not in any region.  Bytes before following region: 4473683968
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                      10aa70000-10ac42000    [ 1864K] r-x/r-x SM=COW  /Users/USER/Downloads/*/pd.x86_64
```

It may not be worth investigating this if it's something very specific to the dongle (it's the official Sony one, if that's any help) - I'm not actually using it to play the game, it's just something that's constantly plugged into my system.

EDIT: Couple more minor bugs

- Sliders for options that utilise sliders do not render, but still function correctly
![Screenshot 2024-11-20 at 1 10 28 pm](https://github.com/user-attachments/assets/ce30b8c6-c0ea-4bcb-ab36-06e959d643cd)

- Text boxes for pickups and subtitles do not render the outline of the box.
![Screenshot 2024-11-20 at 1 06 22 pm](https://github.com/user-attachments/assets/aa61917f-fd28-4819-9a10-e64b478161a7)

**Comment by AJ292** [comment] 2024-11-20 03:38
A couple of Carrington Villa issues:

- Some kind of far clipping plane bug 
![Screenshot 2024-11-20 at 2 30 20 pm](https://github.com/user-attachments/assets/49ff3954-182f-42f2-8a05-9d5cb1e76a67)
![Screenshot 2024-11-20 at 2 31 32 pm](https://github.com/user-attachments/assets/e35e804f-b315-45f8-9caf-a7cb56ca8e05)

- It seems to be really easy to clip the viewport through geometry, simply by walking up to it. It didn't happen in any of the initial dataDyne levels - it's currently unique to Carrington Villa.
![Screenshot 2024-11-20 at 2 34 06 pm](https://github.com/user-attachments/assets/7e74391e-13b3-4d98-aabf-507dfea2ff50) (ignore the mini screenshot in the bottom right hand corner)

![Screenshot 2024-11-20 at 2 34 00 pm](https://github.com/user-attachments/assets/a8e45284-9341-4124-aa5d-3bd24192ecb0)

**Comment by fgsfdsfgs** [comment] 2024-11-20 08:49
Well, this is why it warns about core profile. Assuming the issues are not caused by something else. Unfortunately core profile 3.2/4.1 is the only GL you get on Macs (and 2.1, but that's not enough to run the game), at least as far as I know.
I'll look into making it work properly.

**Comment by fgsfdsfgs** [comment] 2024-11-20 11:09
Pushed a change that should better detect GL core and GLES and use workarounds for some things that are different on them.

**Comment by AJ292** [comment] 2024-11-20 11:16
Ah, the ol' Apple/OpenGL conundrum. Appreciate the extra effort - I'll give the new build a try.

**Comment by AJ292** [comment] 2024-11-20 11:28
Alright, looking good! All the bugs with Carrington Villa are gone, as well as the lack of an outline around text boxes and the non-rendering of options sliders. I do get a handful of errors in Terminal upon launch, which I assume must be functions missing the older versions of GL.

```
WARNING: GL: could not create GL3.0 context: Failed creating OpenGL context at version requested
GL: created GL4.1core context
ERROR: GL: could not find function: glVertexP2ui
ERROR: GL: could not find function: glVertexP2uiv
ERROR: GL: could not find function: glVertexP3ui
ERROR: GL: could not find function: glVertexP3uiv
ERROR: GL: could not find function: glVertexP4ui
ERROR: GL: could not find function: glVertexP4uiv
ERROR: GL: could not find function: glTexCoordP1ui
ERROR: GL: could not find function: glTexCoordP1uiv
ERROR: GL: could not find function: glTexCoordP2ui
ERROR: GL: could not find function: glTexCoordP2uiv
ERROR: GL: could not find function: glTexCoordP3ui
ERROR: GL: could not find function: glTexCoordP3uiv
ERROR: GL: could not find function: glTexCoordP4ui
ERROR: GL: could not find function: glTexCoordP4uiv
ERROR: GL: could not find function: glMultiTexCoordP1ui
ERROR: GL: could not find function: glMultiTexCoordP1uiv
ERROR: GL: could not find function: glMultiTexCoordP2ui
ERROR: GL: could not find function: glMultiTexCoordP2uiv
ERROR: GL: could not find function: glMultiTexCoordP3ui
ERROR: GL: could not find function: glMultiTexCoordP3uiv
ERROR: GL: could not find function: glMultiTexCoordP4ui
ERROR: GL: could not find function: glMultiTexCoordP4uiv
ERROR: GL: could not find function: glNormalP3ui
ERROR: GL: could not find function: glNormalP3uiv
ERROR: GL: could not find function: glColorP3ui
ERROR: GL: could not find function: glColorP3uiv
ERROR: GL: could not find function: glColorP4ui
ERROR: GL: could not find function: glColorP4uiv
ERROR: GL: could not find function: glSecondaryColorP3ui
ERROR: GL: could not find function: glSecondaryColorP3uiv
GL: using GLSL version 410 core
WARNING: GL: using core profile or ES, watch out for errors  
```

I haven't noticed anything different (except maybe the geometry seams are showing the gaps more prominently than before, but I might be imagining it. Plus, I recall another thread regarding it not being a particularly fixable issue anyway). I will keep playing and report back.

**Comment by fgsfdsfgs** [comment] 2024-11-20 11:30
Yeah the missing functions are fine, they are not used in the port. Can you run the game with `--debug-gl` in the terminal and paste the output here?

**Comment by AJ292** [comment] 2024-11-20 11:33
```
version: port 3c020ca (x86_64-osx)
startup date: 20 Nov 2024 22:31:27
base dir: ./data
save dir: .
2024-11-20 22:31:28.601 pd.x86_64[23397:821752] +[IMKClient subclass]: chose IMKClient_Modern
2024-11-20 22:31:28.601 pd.x86_64[23397:821752] +[IMKInputSession subclass]: chose IMKInputSession_Modern
WARNING: GL: could not create GL3.0 context: Failed creating OpenGL context at version requested
GL: created GL4.1core context
ERROR: GL: could not find function: glVertexP2ui
ERROR: GL: could not find function: glVertexP2uiv
ERROR: GL: could not find function: glVertexP3ui
ERROR: GL: could not find function: glVertexP3uiv
ERROR: GL: could not find function: glVertexP4ui
ERROR: GL: could not find function: glVertexP4uiv
ERROR: GL: could not find function: glTexCoordP1ui
ERROR: GL: could not find function: glTexCoordP1uiv
ERROR: GL: could not find function: glTexCoordP2ui
ERROR: GL: could not find function: glTexCoordP2uiv
ERROR: GL: could not find function: glTexCoordP3ui
ERROR: GL: could not find function: glTexCoordP3uiv
ERROR: GL: could not find function: glTexCoordP4ui
ERROR: GL: could not find function: glTexCoordP4uiv
ERROR: GL: could not find function: glMultiTexCoordP1ui
ERROR: GL: could not find function: glMultiTexCoordP1uiv
ERROR: GL: could not find function: glMultiTexCoordP2ui
ERROR: GL: could not find function: glMultiTexCoordP2uiv
ERROR: GL: could not find function: glMultiTexCoordP3ui
ERROR: GL: could not find function: glMultiTexCoordP3uiv
ERROR: GL: could not find function: glMultiTexCoordP4ui
ERROR: GL: could not find function: glMultiTexCoordP4uiv
ERROR: GL: could not find function: glNormalP3ui
ERROR: GL: could not find function: glNormalP3uiv
ERROR: GL: could not find function: glColorP3ui
ERROR: GL: could not find function: glColorP3uiv
ERROR: GL: could not find function: glColorP4ui
ERROR: GL: could not find function: glColorP4uiv
ERROR: GL: could not find function: glSecondaryColorP3ui
ERROR: GL: could not find function: glSecondaryColorP3uiv
GL: version: 4.1 ATI-4.8.101
GL: vendor: ATI Technologies Inc.
GL: renderer: AMD Radeon HD - FirePro D700 OpenGL Engine
GL: GLSL version: 4.10
GL: ARB_framebuffer_object: yes
GL: ARB_depth_clamp: no
GL: ARB_texture_mirror_clamp_to_edge: no
GL: using GLSL version 410 core
WARNING: GL: using core profile or ES, watch out for errors
ROM file: pd.ntsc-final.z64
loading segment fontjpnsingle from ROM (offset 00194b20 pointer 0x7fab2d094b20)
loading segment fontjpnmulti from ROM (offset 0019fb40 pointer 0x7fab2d09fb40)
loading segment animations from ROM (offset 001a15c0 pointer 0x7fab2d0a15c0)
loading segment mpconfigs from ROM (offset 007d0a40 pointer 0x7fab2d6d0a40)
loading segment mpstringsE from ROM (offset 007d1c20 pointer 0x7fab2d6d1c20)
loading segment mpstringsJ from ROM (offset 007d5320 pointer 0x7fab2d6d5320)
loading segment mpstringsP from ROM (offset 007d8a20 pointer 0x7fab2d6d8a20)
loading segment mpstringsG from ROM (offset 007dc120 pointer 0x7fab2d6dc120)
loading segment mpstringsF from ROM (offset 007df820 pointer 0x7fab2d6df820)
loading segment mpstringsS from ROM (offset 007e2f20 pointer 0x7fab2d6e2f20)
loading segment mpstringsI from ROM (offset 007e6620 pointer 0x7fab2d6e6620)
loading segment firingrange from ROM (offset 007e9d20 pointer 0x7fab2d6e9d20)
loading segment fonttahoma from ROM (offset 007f7860 pointer 0x7fab2d6f7860)
loading segment fontnumeric from ROM (offset 007f8b20 pointer 0x7fab2d6f8b20)
loading segment fonthandelgothicsm from ROM (offset 007f9d30 pointer 0x7fab2d6f9d30)
loading segment fonthandelgothicxs from ROM (offset 007fbfb0 pointer 0x7fab2d6fbfb0)
loading segment fonthandelgothicmd from ROM (offset 007fdd80 pointer 0x7fab2d6fdd80)
loading segment fonthandelgothiclg from ROM (offset 008008e0 pointer 0x7fab2d7008e0)
loading segment sfxctl from ROM (offset 0080a250 pointer 0x7fab2d70a250)
loading segment sfxtbl from ROM (offset 00839dd0 pointer 0x7fab2d739dd0)
loading segment seqctl from ROM (offset 00cfbf30 pointer 0x7fab2dbfbf30)
loading segment seqtbl from ROM (offset 00d05f90 pointer 0x7fab2dc05f90)
loading segment sequences from ROM (offset 00e82000 pointer 0x7fab2dd82000)
loading segment texturesdata from ROM (offset 01d65f40 pointer 0x7fab2ec65f40)
loading segment textureslist from ROM (offset 01ff7ca0 pointer 0x7fab2eef7ca0)
loading segment copyright from ROM (offset 01ffea20 pointer 0x7fab2eefea20)
skipping segment fontjpn
romdataInit: loaded rom, size = 33554432
memp heap at 0x7fab2ef01000 - 0x7fab2ff01000
rom  file at 0x7fab2cf00000 - 0x7fab2ef00000
input: assigned controller '0: (DUALSHOCK®4 USB Wireless Adaptor)' (id 0) to player 0
```

**Comment by fgsfdsfgs** [comment] 2024-11-20 11:59
Oh, that's funny. I think I know why your controller causes a crash: it has a `®` in the name.
Other than that, kind of disappointing that despite GL being 4.1core on your system it doesn't seem to have `GL_DEPTH_CLAMP`, or at least is not reporting the extension.

Thank you for the info. Can you do the same thing again with the new build that was just uploaded?

**Comment by AJ292** [comment] 2024-11-20 12:04
Ahh joy - thanks Sony! Not something I can change, unfortunately - it's baked into the dongle. No biggie.

Here's the output from Terminal with debug on for the new build:

```
version: port ba1b6c3 (x86_64-osx)
startup date: 20 Nov 2024 23:02:08
base dir: ./data
save dir: .
2024-11-20 23:02:09.137 pd.x86_64[25077:870224] +[IMKClient subclass]: chose IMKClient_Modern
2024-11-20 23:02:09.137 pd.x86_64[25077:870224] +[IMKInputSession subclass]: chose IMKInputSession_Modern
WARNING: GL: could not create GL3.0 context: Failed creating OpenGL context at version requested
GL: created GL4.1core context
ERROR: GL: could not find function: glVertexP2ui
ERROR: GL: could not find function: glVertexP2uiv
ERROR: GL: could not find function: glVertexP3ui
ERROR: GL: could not find function: glVertexP3uiv
ERROR: GL: could not find function: glVertexP4ui
ERROR: GL: could not find function: glVertexP4uiv
ERROR: GL: could not find function: glTexCoordP1ui
ERROR: GL: could not find function: glTexCoordP1uiv
ERROR: GL: could not find function: glTexCoordP2ui
ERROR: GL: could not find function: glTexCoordP2uiv
ERROR: GL: could not find function: glTexCoordP3ui
ERROR: GL: could not find function: glTexCoordP3uiv
ERROR: GL: could not find function: glTexCoordP4ui
ERROR: GL: could not find function: glTexCoordP4uiv
ERROR: GL: could not find function: glMultiTexCoordP1ui
ERROR: GL: could not find function: glMultiTexCoordP1uiv
ERROR: GL: could not find function: glMultiTexCoordP2ui
ERROR: GL: could not find function: glMultiTexCoordP2uiv
ERROR: GL: could not find function: glMultiTexCoordP3ui
ERROR: GL: could not find function: glMultiTexCoordP3uiv
ERROR: GL: could not find function: glMultiTexCoordP4ui
ERROR: GL: could not find function: glMultiTexCoordP4uiv
ERROR: GL: could not find function: glNormalP3ui
ERROR: GL: could not find function: glNormalP3uiv
ERROR: GL: could not find function: glColorP3ui
ERROR: GL: could not find function: glColorP3uiv
ERROR: GL: could not find function: glColorP4ui
ERROR: GL: could not find function: glColorP4uiv
ERROR: GL: could not find function: glSecondaryColorP3ui
ERROR: GL: could not find function: glSecondaryColorP3uiv
GL: version: 4.1 ATI-4.8.101
GL: vendor: ATI Technologies Inc.
GL: renderer: AMD Radeon HD - FirePro D700 OpenGL Engine
GL: GLSL version: 4.10
GL: ARB_framebuffer_object: yes
GL: ARB_depth_clamp: yes
GL: ARB_texture_mirror_clamp_to_edge: no
GL: using GLSL version 410 core
WARNING: GL: using core profile or ES, watch out for errors
ROM file: pd.ntsc-final.z64
loading segment fontjpnsingle from ROM (offset 00194b20 pointer 0x7fe8a0194b20)
loading segment fontjpnmulti from ROM (offset 0019fb40 pointer 0x7fe8a019fb40)
loading segment animations from ROM (offset 001a15c0 pointer 0x7fe8a01a15c0)
loading segment mpconfigs from ROM (offset 007d0a40 pointer 0x7fe8a07d0a40)
loading segment mpstringsE from ROM (offset 007d1c20 pointer 0x7fe8a07d1c20)
loading segment mpstringsJ from ROM (offset 007d5320 pointer 0x7fe8a07d5320)
loading segment mpstringsP from ROM (offset 007d8a20 pointer 0x7fe8a07d8a20)
loading segment mpstringsG from ROM (offset 007dc120 pointer 0x7fe8a07dc120)
loading segment mpstringsF from ROM (offset 007df820 pointer 0x7fe8a07df820)
loading segment mpstringsS from ROM (offset 007e2f20 pointer 0x7fe8a07e2f20)
loading segment mpstringsI from ROM (offset 007e6620 pointer 0x7fe8a07e6620)
loading segment firingrange from ROM (offset 007e9d20 pointer 0x7fe8a07e9d20)
loading segment fonttahoma from ROM (offset 007f7860 pointer 0x7fe8a07f7860)
loading segment fontnumeric from ROM (offset 007f8b20 pointer 0x7fe8a07f8b20)
loading segment fonthandelgothicsm from ROM (offset 007f9d30 pointer 0x7fe8a07f9d30)
loading segment fonthandelgothicxs from ROM (offset 007fbfb0 pointer 0x7fe8a07fbfb0)
loading segment fonthandelgothicmd from ROM (offset 007fdd80 pointer 0x7fe8a07fdd80)
loading segment fonthandelgothiclg from ROM (offset 008008e0 pointer 0x7fe8a08008e0)
loading segment sfxctl from ROM (offset 0080a250 pointer 0x7fe8a080a250)
loading segment sfxtbl from ROM (offset 00839dd0 pointer 0x7fe8a0839dd0)
loading segment seqctl from ROM (offset 00cfbf30 pointer 0x7fe8a0cfbf30)
loading segment seqtbl from ROM (offset 00d05f90 pointer 0x7fe8a0d05f90)
loading segment sequences from ROM (offset 00e82000 pointer 0x7fe8a0e82000)
loading segment texturesdata from ROM (offset 01d65f40 pointer 0x7fe8a1d65f40)
loading segment textureslist from ROM (offset 01ff7ca0 pointer 0x7fe8a1ff7ca0)
loading segment copyright from ROM (offset 01ffea20 pointer 0x7fe8a1ffea20)
skipping segment fontjpn
romdataInit: loaded rom, size = 33554432
memp heap at 0x7fe876201000 - 0x7fe877201000
rom  file at 0x7fe8a0000000 - 0x7fe8a2000000
input: assigned controller '0: (DUALSHOCK®4 USB Wireless Adaptor)' (id 0) to player 0 
```

**Comment by fgsfdsfgs** [comment] 2024-11-20 12:05
Thanks, this checks out. I pushed another change that will hopefully fix the crash. It'll take a few minutes to build.

**Comment by AJ292** [comment] 2024-11-20 12:20
That build has indeed solved the crash! Tested with the controller too and all seems fine. 

Would it be worth adding the information about launching the game to the readme? The average MacOS user probably wouldn't be expecting to launch the game through Terminal, let alone set permissions on the directory.

I'm going to look into what's involved in making this a regular app bundle in the meantime.

**Comment by fgsfdsfgs** [comment] 2024-11-20 12:22
Yes, I will update the README. I will also probably look for a way to make it load frameworks from the current directory instead of making users install them system-wide.

**Comment by AJ292** [comment] 2024-11-20 12:39
Putting frameworks in an app bundle would achieve that, but there'll be other quirks to figure out with that, mainly to do with the location of the ROM.

For now though, I'm very happy there's a MacOS build! I'd already had a whirl on my Windows machine, but it's much more convenient on MacOS for me.

**Comment by fgsfdsfgs** [comment] 2024-11-20 13:12
I've enabled an option that might make it load stuff from the executable directory. Could you try deleting/renaming your system-wide SDL2 install and trying the new build?

**Comment by AJ292** [comment] 2024-11-20 20:34
Unfortunately, it did not work:

```
dyld[1898]: Library not loaded: @rpath/SDL2.framework/Versions/A/SDL2
  Referenced from: <F24615CC-245F-3977-AFAB-58412AEC3EA3> /Users/aj/Downloads/pd-x86_64-osx/pd.x86_64
  Reason: tried: '/Library/Frameworks/SDL2.framework/Versions/A/SDL2' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Library/Frameworks/SDL2.framework/Versions/A/SDL2' (no such file), '/Library/Frameworks/SDL2.framework/Versions/A/SDL2' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Library/Frameworks/SDL2.framework/Versions/A/SDL2' (no such file)
zsh: abort      ./pd.x86_64
```

Annoyingly, a test version that I made locally as an app bundle which included the framework also doesn't work. There might potentially be some info regarding framworks here: https://wiki.freepascal.org/macOS_Frameworks

**Comment by fgsfdsfgs** [comment] 2024-11-21 18:40
Alright, pushed a new one. How about now?

**Comment by AJ292** [comment] 2024-11-21 20:34
Working as intended!

**Comment by fgsfdsfgs** [comment] 2024-11-21 20:51
Cool, thanks for testing. I'll close this since I think all of the OSX issues are solved and packaging is probably a separate issue at this point.

**Closed as completed by fgsfdsfgs** 2024-11-21 20:51 UTC
