### ISSUE TITLE
Unknown OpCode when entering third room in Sector 2 in Datadyne: Investigation

### ISSUE THREAD

**Issue by michael-celani** [fgsfdsfgs/perfect_dark#66] opened 2023-08-20 23:25 UTC
I'm getting an unknown op code when attempting to enter the third door in Sector 2 in Dayadyne: Investigation. Seems related to #30. 

Here is my ini file:
[pd.ini.txt](https://github.com/fgsfdsfgs/perfect_dark/files/12389387/pd.ini.txt)

![image](https://github.com/fgsfdsfgs/perfect_dark/assets/14599077/6f187bc3-f5b3-4f5f-91d4-0dfd3b0f7a24)

**Comment by ghost** [comment] 2023-08-20 23:27
Can confirm it also happens to me.

**Comment by 8sm32K4D1K5f3E** [comment] 2023-08-20 23:30
Confirming, exact same error message exact same place.

**Comment by sylveonsylvia** [comment] 2023-08-20 23:38
same thing on linux 

`gfx: unknown opcode 5, words 05000088 fd100000
pd.exe: port/fast3d/gfx_pc.cpp:2525: void gfx_run_dl(Gfx*): Assertion `0 && "Unknown GBI opcode"' failed.
Aborted (core dumped)`

**Comment by ghost** [comment] 2023-08-20 23:43
This crash does not occur for me on https://github.com/fgsfdsfgs/perfect_dark/actions/runs/5911879185 So something must have been changed between these versions that causes this issue. I will test each artifact until I run into the problematic build

**Comment by ghost** [comment] 2023-08-21 00:02
This appears to have been caused by something with https://github.com/fgsfdsfgs/perfect_dark/actions/runs/5918216853
It does not occur on the previous artifact https://github.com/fgsfdsfgs/perfect_dark/actions/runs/5918039101

EDIT: Looking through the window to the right of the door is fine until you look too far into the left where the item is, perhaps something with it's model is causing an issue.

**Comment by fgsfdsfgs** [comment] 2023-08-21 22:30
This should be fixed now. Was caused by a weird texture inside the IR Goggles model.

**Comment by ghost** [comment] 2023-08-21 22:44
This fixes the unknown opcode error, but now the goggles no longer spawn.

**Comment by fgsfdsfgs** [comment] 2023-08-21 22:45
Did they spawn before?

**Comment by ghost** [comment] 2023-08-21 22:49
They did spawn before with the artifacts before this issue such as https://github.com/fgsfdsfgs/perfect_dark/actions/runs/5918039101
![goggles](https://github.com/fgsfdsfgs/perfect_dark/assets/130617241/f5d1eb66-60a0-4176-86b4-aab7077d74ed)

**Comment by fgsfdsfgs** [comment] 2023-08-21 22:58
Should be fixed now I think. Autobuild is still going though.

**Comment by ghost** [comment] 2023-08-21 23:05
Can confirm it's now spawning correctly without causing an unknown opcode.

**Closed as completed** 2023-08-21 23:35 UTC
