### ISSUE TITLE
Mouselook senstivity affected by zoom and crouch.

### ISSUE THREAD

**Issue by ghost** [fgsfdsfgs/perfect_dark#32] opened 2023-08-19 10:41 UTC
To reproduce: Use any item that grants the player zoom, or crouch. When they try looking around their sensitivity will be lowered, and when using 30x zoom, you can barely use the mouse (Easily done on Villa on Agent/Special Agent).

**Comment by fgsfdsfgs** [comment] 2023-08-19 11:26
Crouching affects sensitivity in the base game and I didn't modify this behavior.
For the zoom though it looks like the problem is that I accidentally multiplied it twice by the FOV ratio.

**Comment by fgsfdsfgs** [comment] 2023-08-19 11:37
I think the zoom problem should now be fixed. I'll think about the crouching thing.

**Comment by Graslu** [comment] 2023-08-19 12:03
Not only crouching, Elvis too - shorter characters have faster sensitivity. This happens on N64, but is fixed in 1964 GEPD so all the sensitivities match.

**Comment by fgsfdsfgs** [comment] 2023-08-19 12:08
Alright, if it's fixed in 1964 GEPD, then I might as well fix it here too.

**Comment by fgsfdsfgs** [comment] 2023-08-19 12:25
Should be disabled now. Tell me if it feels wrong or something.

**Comment by ghost** [comment] 2023-08-19 12:43
It feels a lot better now. In my testing in SP & MP, I didn't notice any issues.

**Comment by fgsfdsfgs** [comment] 2023-08-19 14:15
Okay, I'll close this then. Feel free to reopen if anyone finds out that something broke.

**Closed as completed by fgsfdsfgs** 2023-08-19 14:15 UTC
