### ISSUE TITLE
[MacOS] Shiny surfaces showing skybox texture when lights are off

### ISSUE THREAD

**Issue by AJ292** [fgsfdsfgs/perfect_dark#546] opened 2024-12-03 06:25 UTC
Currently trying to see if I can see this in any other stages, but in dataDyne Extraction, if you turn Night Vision off and look at the silvery trim pieces, you can see the skybox texture.

![Screenshot 2024-12-03 at 5 19 42 pm](https://github.com/user-attachments/assets/e3da1e18-5076-4f6d-80d1-cb53c561589d)
![Screenshot 2024-12-03 at 5 19 31 pm](https://github.com/user-attachments/assets/b389d462-30d8-43ad-b84f-ffe9d69ff1c4)

Using the latest build as of posting.

**Comment by ZenithMDC** [comment] 2024-12-03 14:33
Just tested 238649403. I can confirm that this happens for me on Windows 10, so it's not exclusive to MacOS. Also tested `port-pre-64` 2a5c3a351 and happens there, too. And now, just tested the N64 version and it does **NOT** happen.

With the `Perfect Darkness` cheat enabled, it's possible for this to occur on any level that has a shiny metallic texture. For instance, I turned that cheat on and played Carrington Institute: Defense. The CI monument right near the start was treated like a skybox.

**Comment by fgsfdsfgs** [comment] 2024-12-03 16:01
This is not OSX specific. nor 64-bit specific. Known issue (#404, #101). I'll close this as a dupe.

**Closed as not planned** 2024-12-03 16:01 UTC
